const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const defaults={machine:'',crop:'',customer:'',hc:'ON',condition:'Normal',symptoms:[],sample:'Clean',tailings:'Not checked',
setup:{rotor:'500',concave:'20',vanes:'Middle / baseline',fan:'950',presieve:'5',upper:'12',lower:'8',speed:'4.0',load:'75'},pan:{density:'',yield:'',cut:'',discharge:'',speed:'',area:'',grams:'',main:'Not sure',notes:''},saved:[]};
let S=JSON.parse(localStorage.getItem('optimizerPro')||'null')||defaults,page='home';
const app=document.getElementById('app');
S.setup={...defaults.setup,...(S.setup||{})};
const machines=['8230','8240','8250','9230','9240','9250','AF9','AF10','AF11'];
const crops=['Canola','Wheat','Barley','Oats','Peas','Lentils','Flax','Soybeans','Corn','Other'];
const densities={Canola:50,Wheat:60,Barley:48,Oats:34,Peas:60,Lentils:60,Flax:56,Soybeans:60,Corn:56};
const symptoms=['Unthreshed grain / heads / pods','Rotor loss / free grain in straw','Sieve loss / free grain in chaff','Cracked / broken grain','Dirty sample / MOG','Stalks / straw in grain tank','High tailings','Grain blowing out','Poor capacity','Plugging / overloading','Uneven / hill loss','Harvest Command hunting'];
function save(){localStorage.setItem('optimizerPro',JSON.stringify(S));status()}
function status(){$('#status').textContent=`${S.machine||'No machine'} • ${S.crop||'No crop'}${S.customer?' • '+S.customer:''}`}
function card(t,b){return `<section class="card"><h2>${t}</h2>${b}</section>`}
function sel(label,key,arr,obj=S){return `<label>${label}</label><select data-key="${key}">${arr.map(x=>`<option ${obj[key]===x?'selected':''}>${x}</option>`).join('')}</select>`}
function inp(label,key,obj=S,type='text'){return `<label>${label}</label><input type="${type}" data-key="${key}" value="${obj[key]??''}">`}
function bind(obj=S){$$('[data-key]').forEach(e=>e.onchange=()=>{obj[e.dataset.key]=e.value;save();if(page==='information'||page==='recommend'||page==='pans')render()})}
function home(){const body=inp('Customer','customer')+sel('Machine','machine',['',...machines])+sel('Crop','crop',['',...crops])+sel('Harvest Command','hc',['ON','OFF'])+sel('Crop / field condition','condition',['Normal','Dry / brittle','Tough / damp','Heavy crop','Light crop','Hilly / uneven']);app.innerHTML=`<h1>Home</h1>${card('Field Setup',body)}`;bind()}
function diagnose(){const checks=symptoms.map(x=>`<label class="check"><input type="checkbox" data-sym="${x}" ${S.symptoms.includes(x)?'checked':''}><span>${x}</span></label>`).join('');const body=checks+sel('Grain sample','sample',['Clean','Unthreshed material','Cracked / damaged grain','Dirty / high MOG','Stalks / straw'])+sel('Tailings / returns','tailings',['Not checked','Mostly clean grain','Unthreshed heads / pods','Chaff / MOG','Damaged grain','Sudden high volume']);app.innerHTML=`<h1>Diagnose</h1>${card('What are you seeing?',body)}<button class="btn" data-go="recommend">BUILD RECOMMENDATIONS</button>`;bind();$$('[data-sym]').forEach(e=>e.onchange=()=>{S.symptoms=e.checked?[...new Set([...S.symptoms,e.dataset.sym])]:S.symptoms.filter(x=>x!==e.dataset.sym);save()})}
function pans(){if(!S.pan.density&&densities[S.crop])S.pan.density=densities[S.crop];const p=S.pan,n=v=>Number(v)||0,area=n(p.area),g=n(p.grams),density=n(p.density),cut=n(p.cut),dis=n(p.discharge);let lb=0,bu=0,pct=0;if(area&&g&&density&&cut&&dis){lb=(g/area)*43560/453.59237*(dis/cut);bu=lb/density;pct=n(p.yield)?bu/n(p.yield)*100:0}app.innerHTML=`<h1>Drop Pans</h1><div class="note">Enter the actual catch area and collected loss weight. The calculator estimates field loss after correcting discharge width to cut width.</div>${card('Combine Loss Results',`<div class="grid2">${inp('Density / test weight (lb/bu)','density',p,'number')}${inp('Yield (bu/ac)','yield',p,'number')}${inp('Cut width (ft)','cut',p,'number')}${inp('Discharge width (ft)','discharge',p,'number')}${inp('Ground speed (mph)','speed',p,'number')}${inp('Catch area (ft²)','area',p,'number')}${inp('Loss weight (grams)','grams',p,'number')}</div><div class="result"><div><b>${bu.toFixed(2)}</b><small>bu/ac loss</small></div><div><b>${pct.toFixed(2)}%</b><small>yield loss</small></div><div><b>${lb.toFixed(1)}</b><small>lb/ac</small></div></div>`)}${card('Physical Classification',`${sel('Main physical loss location','main',['Not sure','Header','Rotor / separation','Cleaning system','No significant physical loss'],p)}<label>Notes</label><textarea data-key="notes">${p.notes||''}</textarea><button class="btn" data-go="recommend">BUILD FINAL RECOMMENDATIONS</button>`)}`;bind(p)}
function currentSettings(){return `${inp('Rotor RPM','rotor',S.setup,'number')}${inp('Concave clearance','concave',S.setup,'number')}${sel('Cage vane position / retention','vanes',['Faster crop travel','Middle / baseline','More retention'],S.setup)}${inp('Fan RPM','fan',S.setup,'number')}${inp('Pre-sieve opening','presieve',S.setup,'number')}${inp('Upper sieve opening','upper',S.setup,'number')}${inp('Lower sieve opening','lower',S.setup,'number')}${inp('Ground speed (mph)','speed',S.setup,'number')}${inp('Engine load (%)','load',S.setup,'number')}`}
function information(){
 const family=(S.machine||'').startsWith('AF')?'AF Series':'8230–9250 Axial-Flow';
 const items=[
 ['Feeder faceplate','Mounts the header to the feeder. Its angle affects header geometry and how smoothly crop enters the feeder. Header height, tilt and faceplate setup must be correct before blaming threshing or cleaning.','Both'],
 ['Feeder chain','Uses slats/chains to carry the crop mat rearward from the header into the transition area. Even, continuous feeding is important because bunches create rotor-load spikes and unstable loss.','Both'],
 ['Feeder slats','The crossbars attached to the feeder chain physically grip and move the crop mat. Bent, worn or missing slats can make feeding uneven.','Both'],
 ['Feeder drive','Powers the feeder and header. On equipped machines feedrate/drive control works with machine load; overload protection and reversing help clear plugs.','Both'],
 ['Feeder reverser / deslug function','Reverses crop flow to help remove a feeder or rotor slug instead of forcing more material into the machine. Use only according to the machine procedure.','Both'],
 ['Stone trap / rock protection','Intercepts stones before they reach the threshing system. On AF Series, the Synchronized Feed System also improves rock-catching function and remote stone-trap dumping can be equipped.','Both'],
 ['Synchronized Feed System (SFS)','AF Series system that times feeder-chain delivery with rotor speed so crop transfers smoothly into the transition cone, reducing bunching and grain damage.','AF Series'],
 ['Transition cone','Funnels the wide crop mat from the feeder into the narrower axial rotor path. Wear or damage here changes crop acceleration and can contribute to poor feeding or plugging.','Both'],
 ['Rotor','The main axial threshing/separating element. Crop spirals around it; threshing occurs mainly as crop is rubbed against concaves, then centrifugal force helps separated grain move through concaves/grates. 8230–9250 use the established single-rotor layout; AF9/AF10 use the longer AFXL single rotor while AF11 uses AFXL2 dual rotors.','Both'],
 ['Rotor rasp bars','Raised rotor elements that engage, accelerate and rub crop. Their type, position and wear affect threshing aggression, crop movement, grain damage and separation.','Both'],
 ['Spiked rasp / separation bars','More aggressive rotor elements used where additional crop agitation/separation is required. They are not the same job as the standard threshing rasp bars.','Both'],
 ['HX rasp bars','AF AFXL rotor elements in the transition between threshing and separation; Case IH describes them as combining spiked-bar height with a standard-bar profile to accelerate crop flow between zones.','AF Series'],
 ['Rotor speed','Changes rotor tip speed and crop agitation. More speed can improve threshing but can increase damage or break MOG; less speed can protect grain but may reduce threshing/separation. Diagnose the physical loss before changing it.','Both'],
 ['Concaves','Curved grates directly under/around the threshing section of the rotor. They provide the opposing surface for threshing and openings for released grain to leave the crop mat. Concave type must suit crop/conditions.','Both'],
 ['Concave clearance','Gap between rotor and concaves. Tighter generally increases rubbing/threshing; wider reduces aggression. It is a separate adjustment from rotor speed.','Both'],
 ['Separating grates','Grated area after the main threshing concaves. Their job is primarily to give already-loose grain more opportunity to leave the straw mat before residue exits the rotor.','Both'],
 ['Rotor cage','Stationary structure surrounding the rotor that contains and guides the crop mat through the axial path.','Both'],
 ['Rotor cage vanes','Guide crop rearward through the rotor cage. More retention increases time/opportunity in the rotor; a faster crop-travel position moves material rearward sooner. Harvest Command can control vane angle on equipped machines.','Both'],
 ['Active grain pan','Receives grain and MOG that have passed through concaves/grates and uses reciprocating motion to begin stratifying/separating the material before final cleaning.','8230–9250'],
 ['Grain-pan sidehill distribution','On AF Series the cleaning architecture includes active cross-distribution control at the grain pan so material is kept more evenly distributed on slopes.','AF Series'],
 ['Pre-sieve','First adjustable cleaning opening encountered by material entering the shoe on 250-series architecture. It can let readily clean grain fall toward the lower sieve early, reducing upper-sieve load. Too closed restricts capacity; too open can pass excess MOG.','8230–9250'],
 ['Upper front sieve','AF Series Harvest Command controls the front portion independently. It is an individual cleaning element and is not the same adjustment as the rear upper sieve.','AF Series'],
 ['Upper rear sieve','Rear section of the AF upper cleaning area. Independent control lets the machine match opening to material condition and load through the rear of the shoe.','AF Series'],
 ['Lower front sieve','Front lower-sieve section on AF Series. Clean grain must pass through it while larger unwanted material is retained for further processing/rejection.','AF Series'],
 ['Lower rear sieve','Rear lower-sieve section on AF Series. It is separately controlled from the front lower section by Harvest Command.','AF Series'],
 ['Upper sieve / chaffer','On 8230–9250, the upper adjustable sieve carries the bulk of the crop mat while air lifts light MOG. Grain falls through its openings. Closing it too far can restrict capacity and increase returns/loss.','8230–9250'],
 ['Lower sieve / shoe sieve','Final adjustable cleaning stage on 8230–9250. Clean grain passes through toward the clean-grain auger while larger material is directed toward the returns path.','8230–9250'],
 ['Cross Flow cleaning fan','Supplies cleaning air across the shoe. Case IH uses top-entry/full-width airflow to create a balanced air stream. Too little air leaves light MOG in the sample; excessive air can carry light grain out.','Both'],
 ['Cross Flow Plus cleaning fan','AF Series hydraulically driven fan is larger and designed for high uniform airflow at lower overall fan speeds than the prior architecture.','AF Series'],
 ['Cleaning side shake','AF Series Harvest Command can alter Cross-Flow Plus side-shake/cross-distribution action to keep the shoe loaded evenly as terrain changes.','AF Series'],
 ['Self-leveling cleaning system','On 250-series machines the cleaning system can compensate for side slopes up to about 12%, keeping material distributed rather than piled on the downhill side.','8230–9250'],
 ['Clean-grain cross auger','Collects grain that has passed through the cleaning sieves and moves it sideways to the clean-grain elevator.','Both'],
 ['Second clean-grain cross auger','AF Series uses two strategically positioned clean-grain cross augers to move the much higher cleaning-system throughput to the elevator.','AF Series'],
 ['Clean-grain elevator','Raises cleaned grain from the bottom of the machine to the grain tank/fill system. AF Series uses molded paddles and an all-belt drive with two capacity speeds.','Both'],
 ['Yield sensor','Measures grain-flow force/mass-flow in the clean-grain path so the display can calculate yield when combined with speed, width and calibration information.','Both'],
 ['Moisture sensor','Samples harvested grain to estimate grain moisture. Moisture affects wet-yield correction and the usefulness of yield mapping.','Both'],
 ['Grain quality camera / imaging','Views grain in the clean-grain stream and evaluates sample quality. Harvest Command uses grain-quality information together with other sensors to optimize settings; AF Series can show grain-quality imaging on Pro 1200.','Both'],
 ['Grain tank fill system','Receives grain from the clean-grain elevator and distributes it into the tank so the machine can continue harvesting between unloads.','Both'],
 ['Grain tank','Stores cleaned grain. Capacity is a storage function, not a cleaning function; grain arriving here should already have passed the cleaning system.','Both'],
 ['Grain-tank cross augers','Move grain at the bottom of the tank toward the unloading system. Their job begins only when unloading is commanded.','Both'],
 ['Vertical unload auger','Raises grain from the tank cross-auger area into the horizontal unloading tube.','Both'],
 ['Horizontal unloading auger','Carries grain outward to the cart/truck. Unload capacity is separate from harvesting throughput, although slow unloading can reduce field efficiency.','Both'],
 ['Pivoting unload spout','Controls the discharge trajectory at the end of equipped unloading augers, helping place grain accurately in a cart.','Both'],
 ['Tailings cross auger','Collects material rejected by the cleaning system that still contains recoverable grain and moves it into the returns/reprocessing system.','8230–9250'],
 ['Tri-Sweep tailings processor','Uses three sets of impellers to gently re-thresh tailings, then returns the processed material to the active grain pan for another cleaning pass. This avoids sending the entire return stream back through the main rotor.','8230–9250'],
 ['Tailings volume / returns sensing','Shows how much material is being recirculated. High returns are a symptom, not a setting: inspect what the returns contain—clean grain, unthreshed material or MOG—before adjusting the machine.','Both'],
 ['Residue discharge from rotor','After useful grain has been separated, the remaining straw leaves the rear of the rotor/cage and enters the residue-management path.','Both'],
 ['Integral straw chopper','Cuts rotor residue before spreading. Chop quality depends on rotor/knife condition, crop moisture, throughput and the selected residue configuration.','8230–9250'],
 ['Rotating chopper knives','High-speed moving knives on the chopper rotor that cut straw as it passes through. Sharpness, damage and balance matter for chop quality and vibration.','8230–9250'],
 ['Stationary knives / counterknives','Fixed knives engaged into the chopper crop stream so rotating knives shear residue against them. More knife engagement generally creates a finer chop but requires more power.','Both'],
 ['Xtra-Chopping system','250-series residue option intended for more intensive residue processing than the integral-chopper arrangement.','8230–9250'],
 ['MagnaCut','AF Series integrated chopper option for standard chopping. Case IH pairs it with disc or advanced horizontal spreading options depending on configuration.','AF Series'],
 ['MagnaChop','AF Series high hood-mounted fine-chop option for heavier straw volumes. It supports remote speed selection, chop/drop selection and remote counterknife engagement on applicable configurations.','AF Series'],
 ['Chaff path','Light material separated by the cleaning system leaves the shoe independently of the straw leaving the rotor, then is directed into the selected residue spreading/windrowing arrangement.','Both'],
 ['Chaff spreader','Spreads cleaning-system chaff across the harvested width instead of concentrating it behind the combine.','8230–9250'],
 ['Simple disc spreaders','AF residue option using rotating discs to distribute processed residue behind the combine.','AF Series'],
 ['Advanced horizontal spreaders','AF residue option designed for wide, controlled residue distribution and compatible with the higher-capacity chopping packages.','AF Series'],
 ['Radar Spread Automation','AF Series radar-based control adjusts residue spreading to maintain a more uniform pattern as wind or slope changes.','AF Series'],
 ['Windrow / swath chute','Routes long straw into a windrow instead of chopping/spreading it when straw is being saved.','Both'],
 ['Harvest Command','Automation system that uses sensors and algorithms to adjust machine settings toward the selected strategy. On 250 Series it controls items including rotor speed, cage vanes, fan, sieves and feedrate; AF Series expands control to nine settings including four individual sieve sections and cleaning side shake.','Both'],
 ['Sieve pressure sensors','Measure cleaning-system loading/pressure so Harvest Command can recognize how hard the shoe is working and react before loss becomes excessive.','Both'],
 ['Rotor loss sensors','Detect impacts associated with grain leaving in the separation/residue area. They are a relative electronic indicator and should be calibrated/verified against physical loss checks.','Both'],
 ['Sieve loss sensors','Detect grain impacts at the rear cleaning-loss area. Their monitor reading is not a direct bu/ac measurement; verify with pans/ground counts.','Both'],
 ['Engine load sensing','Tells automation how heavily the engine is loaded. Harvest Command can use a maximum engine-load target to manage feedrate.','Both'],
 ['Ground speed / feedrate control','Changes how much crop enters per unit time. If physical loss rises only as load increases and improves when slowing, total machine capacity may be the limiting factor.','Both'],
 ['PowerPlus CVT rotor drive','Variable rotor drive used on equipped Case IH combines; it allows controlled rotor-speed changes and, on newer architecture, contributes to powered deslug/reversing functions.','Both'],
 ['Pro 700 / Pro 1200 display','Operator interface for machine settings, automation, loss monitors, yield/moisture information, guidance and diagnostics. Model/year determines which display and functions are available.','Both'],
 ['Harvest loss monitor','Combines calibrated electronic loss-sensor signals into an operator reference. It shows change/trend, not an automatically trustworthy field-loss number; physical checks remain the verification.','Both']
 ];
 const shown=items.filter(x=>x[2]==='Both'||x[2]===family);
 const q=(document.getElementById('infoSearch')?.value||'').toLowerCase();
 const filtered=q?shown.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q)):shown;
 app.innerHTML='<h1>Combine Information</h1><div class="note"><b>'+(S.machine||'Select a machine on Home')+'</b> • '+family+'. Every component is listed individually so you can learn exactly what it does. Machine/year/options can change hardware, so use the operator/parts manual for serial-number-specific service information.</div>'+
 '<input id="infoSearch" class="infoSearch" placeholder="Search component — rotor, pre-sieve, Tri-Sweep, chopper...">'+
 '<div class="infoCount">'+filtered.length+' individual components shown</div>'+
 filtered.map(x=>'<section class="card infoCard"><h2>'+x[0]+'</h2><div class="familyTag">'+x[2]+'</div><p>'+x[1]+'</p></section>').join('');
 const box=document.getElementById('infoSearch'); if(box){box.value=q;box.oninput=()=>{const v=box.value;information();const n=document.getElementById('infoSearch');n.value=v;n.focus();n.setSelectionRange(v.length,v.length)}}
}
function recommendations(){let r=[];const has=x=>S.symptoms.includes(x);if(has('Unthreshed grain / heads / pods')||S.sample==='Unthreshed material'||S.tailings==='Unthreshed heads / pods')r.push(['THRESHING','Verify grain is still attached. Test more effective threshing with rotor speed and/or concave clearance. Make one change, then physically verify.']);if(has('Rotor loss / free grain in straw')||S.pan.main==='Rotor / separation')r.push(['SEPARATION','Loose grain with straw points to separation. Check crop load and separation opportunity; test rotor/cage-vane strategy from the current baseline and verify with pans.']);if(has('Sieve loss / free grain in chaff')||has('Grain blowing out')||S.pan.main==='Cleaning system')r.push(['CLEANING','Loose grain with chaff points to the cleaning system. Determine whether the shoe is overloaded or airflow is carrying grain out before changing fan or sieve openings.']);if(has('Cracked / broken grain')||S.sample==='Cracked / damaged grain')r.push(['GRAIN DAMAGE','Reduce unnecessary threshing/rethreshing. Check rotor aggression, concave clearance and whether clean grain is being recirculated in tailings.']);if(has('Dirty sample / MOG')||S.sample==='Dirty / high MOG')r.push(['DIRTY SAMPLE','Identify whether MOG is being created upstream by aggressive threshing or not removed by the cleaning system. Do not automatically close sieves first.']);if(S.tailings==='Mostly clean grain')r.push(['TAILINGS','Mostly clean grain in returns can indicate cleaning restriction. Check sieve openings and loading before increasing threshing aggression.']);if(!r.length)r.push(['VERIFY FIRST','Physically classify the problem: attached grain = threshing, loose grain with straw = separation, loose grain with chaff = cleaning. Then make one change and recheck.']);app.innerHTML=`<h1>Recommendations</h1><div class="note"><b>One change at a time.</b> Confirm the physical loss location before chasing monitor numbers.</div>${card('Ranked Diagnostic Direction',r.map((x,i)=>`<div class="rec"><h3>${i+1}. ${x[0]}</h3><p>${x[1]}</p></div>`).join(''))}<button class="btn" id="saveSetup">SAVE THIS SETUP</button>`;$('#saveSetup').onclick=()=>{S.saved.unshift({date:new Date().toLocaleDateString(),machine:S.machine,crop:S.crop,customer:S.customer,setup:{...S.setup},note:r[0][0]});S.saved=S.saved.slice(0,30);save();alert('Setup saved')}}
function setups(){app.innerHTML=`<h1>Saved Setups</h1>${S.saved.length?S.saved.map(x=>card(`${x.machine||'Machine'} • ${x.crop||'Crop'}`,`<b>${x.customer||'No customer'}</b><div class="muted">${x.date} • ${x.note}</div><p>Rotor ${x.setup.rotor||'—'} • Concave ${x.setup.concave||'—'} • Fan ${x.setup.fan||'—'} • Pre-sieve ${x.setup.presieve||'—'} • Upper ${x.setup.upper||'—'} • Lower ${x.setup.lower||'—'}</p>`)).join(''):card('No saved setups','Save a setup from the Recommendations tab after you have verified it in the field.')}`}
const pages={home,diagnose,pans,information,recommend:recommendations,setups};
function render(){pages[page]();status();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()})}
$$('#nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
window.addEventListener('online',offline);window.addEventListener('offline',offline);
function offline(){const e=$('#offlineStatus');e.textContent=navigator.onLine?'OFFLINE READY ✓':'OFFLINE MODE ✓';e.style.background=navigator.onLine?'#286c37':'#7a1d1d'}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').then(()=>offline()).catch(()=>{$('#offlineStatus').textContent='OFFLINE CACHE ERROR'});
render();offline();
