const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const defaults={machine:'',crop:'',customer:'',hc:'ON',condition:'Normal',symptoms:[],sample:'Clean',tailings:'Not checked',
setup:{rotor:'500',concave:'20',vanes:'Middle / baseline',fan:'950',presieve:'5',upper:'12',lower:'8',speed:'4.0',load:'75'},pan:{density:'',yield:'',cut:'',discharge:'',speed:'',area:'',grams:'',main:'Not sure',notes:''},saved:[]};
let S=JSON.parse(localStorage.getItem('optimizerPro')||'null')||defaults,page='home';
const app=document.getElementById('app');
S.setup={...defaults.setup,...(S.setup||{})};
const machines=['8230','8240','8250','9230','9240','9250','AF9','AF10','AF11'];
const crops=['Canola','Wheat','Barley','Oats','Peas','Lentils','Flax','Soybeans','Corn','Other'];
const densities={Canola:50,Wheat:60,Barley:48,Oats:34,Peas:60,Lentils:60,Flax:56,Soybeans:60,Corn:56};
const symptoms=['Unthreshed grain / heads / pods','Rotor loss / free grain in straw','Sieve loss / free grain in chaff','Cracked / broken grain','Dirty sample / MOG','Stalks / straw in grain tank','High tailings','Grain blowing out','Poor capacity','Plugging / overloading','Uneven / hill loss','Harvest Command hunting'];
function save(){localStorage.setItem('optimizerPro',JSON.stringify(S));status()}
function status(){$('#status').textContent=`${S.machine||'No machine'} • ${S.crop||'No crop'}${S.customer?' • '+S.customer:''}`}
function card(t,b){return `<section class="card"><h2>${t}</h2>${b}</section>`}
function sel(label,key,arr,obj=S){return `<label>${label}</label><select data-key="${key}">${arr.map(x=>`<option ${obj[key]===x?'selected':''}>${x}</option>`).join('')}</select>`}
function inp(label,key,obj=S,type='text'){return `<label>${label}</label><input type="${type}" data-key="${key}" value="${obj[key]??''}">`}
function bind(obj=S){$$('[data-key]').forEach(e=>e.onchange=()=>{obj[e.dataset.key]=e.value;save();if(page==='simulator'||page==='recommend'||page==='pans')render()})}
function home(){const body=inp('Customer','customer')+sel('Machine','machine',['',...machines])+sel('Crop','crop',['',...crops])+sel('Harvest Command','hc',['ON','OFF'])+sel('Crop / field condition','condition',['Normal','Dry / brittle','Tough / damp','Heavy crop','Light crop','Hilly / uneven']);app.innerHTML=`<h1>Home</h1>${card('Field Setup',body)}`;bind()}
function diagnose(){const checks=symptoms.map(x=>`<label class="check"><input type="checkbox" data-sym="${x}" ${S.symptoms.includes(x)?'checked':''}><span>${x}</span></label>`).join('');const body=checks+sel('Grain sample','sample',['Clean','Unthreshed material','Cracked / damaged grain','Dirty / high MOG','Stalks / straw'])+sel('Tailings / returns','tailings',['Not checked','Mostly clean grain','Unthreshed heads / pods','Chaff / MOG','Damaged grain','Sudden high volume']);app.innerHTML=`<h1>Diagnose</h1>${card('What are you seeing?',body)}<button class="btn" data-go="recommend">BUILD RECOMMENDATIONS</button>`;bind();$$('[data-sym]').forEach(e=>e.onchange=()=>{S.symptoms=e.checked?[...new Set([...S.symptoms,e.dataset.sym])]:S.symptoms.filter(x=>x!==e.dataset.sym);save()})}
function pans(){if(!S.pan.density&&densities[S.crop])S.pan.density=densities[S.crop];const p=S.pan,n=v=>Number(v)||0,area=n(p.area),g=n(p.grams),density=n(p.density),cut=n(p.cut),dis=n(p.discharge);let lb=0,bu=0,pct=0;if(area&&g&&density&&cut&&dis){lb=(g/area)*43560/453.59237*(dis/cut);bu=lb/density;pct=n(p.yield)?bu/n(p.yield)*100:0}app.innerHTML=`<h1>Drop Pans</h1><div class="note">Enter the actual catch area and collected loss weight. The calculator estimates field loss after correcting discharge width to cut width.</div>${card('Combine Loss Results',`<div class="grid2">${inp('Density / test weight (lb/bu)','density',p,'number')}${inp('Yield (bu/ac)','yield',p,'number')}${inp('Cut width (ft)','cut',p,'number')}${inp('Discharge width (ft)','discharge',p,'number')}${inp('Ground speed (mph)','speed',p,'number')}${inp('Catch area (ft²)','area',p,'number')}${inp('Loss weight (grams)','grams',p,'number')}</div><div class="result"><div><b>${bu.toFixed(2)}</b><small>bu/ac loss</small></div><div><b>${pct.toFixed(2)}%</b><small>yield loss</small></div><div><b>${lb.toFixed(1)}</b><small>lb/ac</small></div></div>`)}${card('Physical Classification',`${sel('Main physical loss location','main',['Not sure','Header','Rotor / separation','Cleaning system','No significant physical loss'],p)}<label>Notes</label><textarea data-key="notes">${p.notes||''}</textarea><button class="btn" data-go="recommend">BUILD FINAL RECOMMENDATIONS</button>`)}`;bind(p)}
function currentSettings(){return `${inp('Rotor RPM','rotor',S.setup,'number')}${inp('Concave clearance','concave',S.setup,'number')}${sel('Cage vane position / retention','vanes',['Faster crop travel','Middle / baseline','More retention'],S.setup)}${inp('Fan RPM','fan',S.setup,'number')}${inp('Pre-sieve opening','presieve',S.setup,'number')}${inp('Upper sieve opening','upper',S.setup,'number')}${inp('Lower sieve opening','lower',S.setup,'number')}${inp('Ground speed (mph)','speed',S.setup,'number')}${inp('Engine load (%)','load',S.setup,'number')}`}
function simulator(){
 const s=S.setup,n=v=>Number(v)||0,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
 const rotor=n(s.rotor)||500,conc=n(s.concave)||20,fan=n(s.fan)||950,pre=n(s.presieve)||5,upper=n(s.upper)||12,lower=n(s.lower)||8,speed=n(s.speed)||4,load=n(s.load)||75;
 const retention=s.vanes==='More retention'?1.18:(s.vanes==='Faster crop travel'?0.84:1);
 const thresh=cl(62+(rotor-450)*.055-(conc-20)*.8,20,98),sep=cl((76+(rotor-500)*.025-speed*2.5)*retention,20,98);
 const air=cl(48+(fan-700)*.065,20,98),shoe=cl(76+(pre-5)*1.1+(upper-12)*.8+(lower-8)*.6-Math.max(0,load-80)*.8,20,98);
 const clean=cl(78+(air-50)*.22-Math.abs(upper-12)*.55-Math.max(0,pre-10)*.7,45,99),loss=cl((100-sep)*.16+(100-shoe)*.18+Math.max(0,air-84)*.3,1,40);
 const damage=cl(4+Math.max(0,rotor-600)*.035+Math.max(0,15-conc)*.8,1,35);
 app.innerHTML='<h1>Photorealistic X-Ray Crop Flow</h1><div class="note"><b>Live machine cutaway:</b> the photorealistic combine is now the simulator base. Animated overlays show crop, grain, MOG and airflow through the actual machine layout.</div>'+
 card((S.machine||'Combine')+' • '+(S.crop||'Crop'),
 '<div class="photoSim" style="--rotorDur:'+cl(70/rotor,.08,.22)+'s;--airPower:'+cl(air/100,.35,1)+';--flowDur:'+cl(1.8-speed*.16,.65,1.5)+'s">'+
 '<img class="photoCombine" src="./combine-xray-github.jpg?v=10" alt="Photorealistic x-ray combine crop flow">'+
 '<div class="hot feederHot"><b>1</b><span>FEEDER</span></div><div class="hot rotorHot"><b>2</b><span>ROTOR + CONCAVES</span></div><div class="hot panHot"><b>3</b><span>GRAIN PAN</span></div><div class="hot shoeHot"><b>4</b><span>CLEANING SHOE</span></div><div class="hot tankHot"><b>5</b><span>CLEAN GRAIN</span></div><div class="hot residueHot"><b>6</b><span>RESIDUE</span></div>'+
 '<div class="photoCrop cropA"></div><div class="photoCrop cropB"></div><div class="photoCrop cropC"></div>'+
 '<div class="photoGrain grainA"></div><div class="photoGrain grainB"></div><div class="photoGrain grainC"></div>'+
 '<div class="photoAir airA">➜ ➜ ➜</div><div class="photoAir airB">➜ ➜ ➜</div>'+
 '<div class="rotorPulse"></div><div class="photoResidue"></div>'+
 '</div>'+
 '<div class="xrLegend"><b class="grainKey">● Grain</b><b class="strawKey">━ Crop / MOG</b><b class="airKey">➜ Airflow</b></div>'+
 '<div class="simStats"><div><b>'+thresh.toFixed(0)+'%</b><small>Threshing action</small></div><div><b>'+sep.toFixed(0)+'%</b><small>Separation</small></div><div><b>'+clean.toFixed(0)+'%</b><small>Sample clean</small></div><div><b>'+loss.toFixed(1)+'%</b><small>Loss risk</small></div></div>'+
 '<div class="simReadout"><b>Current effect:</b> '+rotor+' rotor rpm • '+conc+' concave • '+fan+' fan rpm • '+speed.toFixed(1)+' mph • '+load+'% load. Damage risk: <strong>'+(damage>18?'HIGH':damage>9?'MODERATE':'LOW')+'</strong>.</div>')+
 card('Live Machine Controls','<div class="grid2">'+currentSettings()+'</div><div class="effectGuide"><b>What changes visually:</b> rotor RPM changes the rotor activity; concave clearance changes separation intensity; fan RPM changes blue airflow strength; pre-sieve and sieve settings change cleaning performance; ground speed/load change crop-flow rate.</div>')+
 card('Crop Flow','<div class="flowSteps"><b>1 FEEDER</b> crop mat enters → <b>2 ROTOR</b> threshing and separation → <b>3 PAN</b> grain/MOG moves to cleaning → <b>4 CLEANING SHOE</b> fan lifts light MOG while grain falls → <b>5 CLEAN GRAIN</b> grain moves to tank → <b>6 RESIDUE</b> straw/chaff exits rear.</div>');
 bind(S.setup);
}
function recommendations(){let r=[];const has=x=>S.symptoms.includes(x);if(has('Unthreshed grain / heads / pods')||S.sample==='Unthreshed material'||S.tailings==='Unthreshed heads / pods')r.push(['THRESHING','Verify grain is still attached. Test more effective threshing with rotor speed and/or concave clearance. Make one change, then physically verify.']);if(has('Rotor loss / free grain in straw')||S.pan.main==='Rotor / separation')r.push(['SEPARATION','Loose grain with straw points to separation. Check crop load and separation opportunity; test rotor/cage-vane strategy from the current baseline and verify with pans.']);if(has('Sieve loss / free grain in chaff')||has('Grain blowing out')||S.pan.main==='Cleaning system')r.push(['CLEANING','Loose grain with chaff points to the cleaning system. Determine whether the shoe is overloaded or airflow is carrying grain out before changing fan or sieve openings.']);if(has('Cracked / broken grain')||S.sample==='Cracked / damaged grain')r.push(['GRAIN DAMAGE','Reduce unnecessary threshing/rethreshing. Check rotor aggression, concave clearance and whether clean grain is being recirculated in tailings.']);if(has('Dirty sample / MOG')||S.sample==='Dirty / high MOG')r.push(['DIRTY SAMPLE','Identify whether MOG is being created upstream by aggressive threshing or not removed by the cleaning system. Do not automatically close sieves first.']);if(S.tailings==='Mostly clean grain')r.push(['TAILINGS','Mostly clean grain in returns can indicate cleaning restriction. Check sieve openings and loading before increasing threshing aggression.']);if(!r.length)r.push(['VERIFY FIRST','Physically classify the problem: attached grain = threshing, loose grain with straw = separation, loose grain with chaff = cleaning. Then make one change and recheck.']);app.innerHTML=`<h1>Recommendations</h1><div class="note"><b>One change at a time.</b> Confirm the physical loss location before chasing monitor numbers.</div>${card('Ranked Diagnostic Direction',r.map((x,i)=>`<div class="rec"><h3>${i+1}. ${x[0]}</h3><p>${x[1]}</p></div>`).join(''))}<button class="btn" id="saveSetup">SAVE THIS SETUP</button>`;$('#saveSetup').onclick=()=>{S.saved.unshift({date:new Date().toLocaleDateString(),machine:S.machine,crop:S.crop,customer:S.customer,setup:{...S.setup},note:r[0][0]});S.saved=S.saved.slice(0,30);save();alert('Setup saved')}}
function setups(){app.innerHTML=`<h1>Saved Setups</h1>${S.saved.length?S.saved.map(x=>card(`${x.machine||'Machine'} • ${x.crop||'Crop'}`,`<b>${x.customer||'No customer'}</b><div class="muted">${x.date} • ${x.note}</div><p>Rotor ${x.setup.rotor||'—'} • Concave ${x.setup.concave||'—'} • Fan ${x.setup.fan||'—'} • Pre-sieve ${x.setup.presieve||'—'} • Upper ${x.setup.upper||'—'} • Lower ${x.setup.lower||'—'}</p>`)).join(''):card('No saved setups','Save a setup from the Recommendations tab after you have verified it in the field.')}`}
const pages={home,diagnose,pans,simulator,recommend:recommendations,setups};
function render(){pages[page]();status();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()})}
$$('#nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
window.addEventListener('online',offline);window.addEventListener('offline',offline);
function offline(){const e=$('#offlineStatus');e.textContent=navigator.onLine?'OFFLINE READY ✓':'OFFLINE MODE ✓';e.style.background=navigator.onLine?'#286c37':'#7a1d1d'}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').then(()=>offline()).catch(()=>{$('#offlineStatus').textContent='OFFLINE CACHE ERROR'});
render();offline();
